### ISSUE TITLE
Type error on  info sindex

### ISSUE THREAD

**Issue by tigran-a** [aerospike/aerospike-admin#27]
in case of a node down : 
```
$ asadm
Aerospike Interactive Shell, version 0.0.13
Found 1 nodes
Offline: 127.0.0.1:3000

Admin> info sindex
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/bin/asadm/__main__.py", line 20, in <module>
  File "/usr/bin/asadm/asadm.py", line 339, in main
  File "/usr/lib/python2.7/cmd.py", line 141, in cmdloop
    line = self.precmd(line)
  File "/usr/bin/asadm/asadm.py", line 108, in precmd
  File "/usr/bin/asadm/lib/controllerlib.py", line 176, in execute
  File "/usr/bin/asadm/lib/controllerlib.py", line 120, in __call__
  File "/usr/bin/asadm/lib/controllerlib.py", line 176, in execute
  File "/usr/bin/asadm/lib/controller.py", line 158, in do_sindex
TypeError: string indices must be integers, not str
```
the same if one node up : 
```
$ asadm -h ...                                                                                                                                              
Aerospike Interactive Shell, version 0.0.13
Found 2 nodes
Online:  10.101.20.20:3000
Offline: 10.101.20.130:3000

Admin> info sindex
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
...
```

**Comment by citrusraj** [comment]
Tigran-a  the issue has already been fixed in release 0.0.15

[TOOLS-152] - Fix "info sindex" crash on offline node
