### ISSUE TITLE
asadm fails when HOME is not set.

### ISSUE THREAD

**Issue by JohanLindvall** [aerospike/aerospike-admin#29]
With $HOME unset, asadm fails with the following error:

Traceback (most recent call last):
File "/usr/lib64/python2.7/runpy.py", line 162, in run_module_as_main
"__main_", fname, loader, pkg_name)
File "/usr/lib64/python2.7/runpy.py", line 72, in run_code
exec code in run_globals
File "/usr/bin/asadm/__main_.py", line 20, in 
File "/usr/bin/asadm/asadm.py", line 476, in main
File "/usr/lib64/python2.7/UserDict.py", line 23, in getitem
raise KeyError(key)
KeyError: 'HOME'

Fixed in https://github.com/aerospike/aerospike-admin/pull/28.

**Comment by citrusraj** [comment]
Fixed in 0.1.10
